### ISSUE TITLE
Error while executing export-surround-to-git script

### ISSUE THREAD

**Issue by rohinigajawada** [JElchison/export-surround-to-git#47]
Below is the error i get:
C:\Program Files (x86)\Seapine\Surround SCM\SSCM_Repo>python C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.p
y -m "[rpt] BnR accounting reports" -p "[rpt] BnR accounting reports/code/"
[+] Beginning parse phase...
Traceback (most recent call last):
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 643, in <module>
    main()
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 638, in main
    handle_command(parser)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 613, in handle_command
    cmd_parse(args.mainline[0], args.path[0], database)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 334, in cmd_parse
    branches = find_all_branches_in_mainline_containing_path(mainline, path)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 172, in find_all_branches_in_mainline_contai
ning_path
    return get_lines_from_sscm_cmd(cmd)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 161, in get_lines_from_sscm_cmd
    sys.stderr.write(stderrdata)
TypeError: write() argument must be str, not bytes

Please help how to fix this error

**Comment by JElchison** [comment]
Hi @rohinigajawada, please don't open a new issue for the same question.  I'll continue this thread at your original question, #46.
